/* world.js — the midden, walkable.
 *
 * First-person walk of the communal world model: the rescued ℚ¹⁶ walk laid
 * out as glowing cells on an abyssal floor, its ancestry edges as lit trails,
 * the verdict round (HONEST GAP @ r7) pulsing ember.
 *
 * Constraints this file is written to:
 *   - opens from file://  → classic script, no modules, no fetch. Data comes
 *     from window.WORLD (generated by tools/gen-world.mjs), Three.js from the
 *     vendored UMD build (vendor/three/three.min.js, r147 — the last release
 *     with a global build).
 *   - no backend, no build step, no assets fetched at runtime: every texture
 *     is drawn into a canvas here.
 *
 * Palette mirrors midden.js / gesture-panel.mjs (Dieter Rams meets Moebius —
 * restraint above the floor, bioluminescence below it). Ember is reserved for
 * the honest gap; everything else is deep-blue bioluminescence and mint.
 */

(function () {
  'use strict';

  var WORLD = window.WORLD;
  var canvas = document.getElementById('world-canvas');

  function fail(msg) {
    var el = document.getElementById('fail');
    el.style.display = 'flex';
    el.textContent = msg;
  }
  if (typeof THREE === 'undefined') {
    fail('the midden could not load three.js — is vendor/three/three.min.js present?');
    return;
  }
  if (!WORLD || !WORLD.rooms || !WORLD.rooms.length) {
    fail('the midden has no floor — world/world-data.js is missing or empty. ' +
         'Regenerate with: node tools/gen-world.mjs');
    return;
  }

  // ── palette ───────────────────────────────────────────────────────────
  var C = {
    deep: 0x04060e,
    floor: 0x071020,
    lattice: 0x16294a,
    blue: 0x1a6fc0,        // bioluminescent blue — real rooms
    blueCore: 0x0b2b4d,
    mint: 0x52f2c8,        // the walk's own glow — trails
    mintDim: 0x2a8f78,
    steel: 0x5a86a8,       // SYNTHETIC — colder, quieter
    steelDim: 0x3a5a76,
    ember: 0xc8561e,       // honest gap only
    emberSoft: 0xe8a34f,
    candor: 0xffd9a0,
    text: 0xcfd8e6,
  };

  var EYE = 1.7;
  var WALK_SPEED = 7.5;
  var RUN_SPEED = 15;
  var AUTO_SPEED = 6;
  var ROOM_RADIUS = 2.7;

  // ── renderer / scene ──────────────────────────────────────────────────
  var renderer;
  try {
    renderer = new THREE.WebGLRenderer({ canvas: canvas, antialias: true });
  } catch (err) {
    fail('the midden needs WebGL: ' + String(err));
    return;
  }
  renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2));
  renderer.setSize(window.innerWidth, window.innerHeight);

  var scene = new THREE.Scene();
  scene.background = new THREE.Color(C.deep);
  scene.fog = new THREE.FogExp2(C.deep, 0.0045);

  var camera = new THREE.PerspectiveCamera(
    72, window.innerWidth / window.innerHeight, 0.1, 1400);
  camera.rotation.order = 'YXZ';
  camera.position.set(0, EYE, 108);

  scene.add(new THREE.AmbientLight(0x0a1428, 2.9));
  var lamp = new THREE.PointLight(0xbfd8ff, 0.95, 34);   // the walker's own lamp
  camera.add(lamp);
  lamp.position.set(0, 0, 0);
  scene.add(camera);
  var roomLight = new THREE.PointLight(C.mint, 0.0, 34);  // lights the room you are near
  scene.add(roomLight);

  // ── small canvas-texture helpers (no runtime assets) ──────────────────
  function haloTexture(inner, outer) {
    var s = 128;
    var cv = document.createElement('canvas');
    cv.width = cv.height = s;
    var g = cv.getContext('2d');
    var grad = g.createRadialGradient(s / 2, s / 2, 0, s / 2, s / 2, s / 2);
    grad.addColorStop(0, inner);
    grad.addColorStop(0.35, outer);
    grad.addColorStop(1, 'rgba(0,0,0,0)');
    g.fillStyle = grad;
    g.fillRect(0, 0, s, s);
    var tex = new THREE.CanvasTexture(cv);
    tex.needsUpdate = true;
    return tex;
  }

  function labelSprite(lines, colorCss, scaleUp) {
    var pad = 26;
    var font = '600 46px ui-monospace, SFMono-Regular, Menlo, Consolas, monospace';
    var cv = document.createElement('canvas');
    var g = cv.getContext('2d');
    g.font = font;
    var w = 0;
    lines.forEach(function (t) { w = Math.max(w, g.measureText(t).width); });
    cv.width = Math.ceil(w + pad * 2);
    cv.height = Math.ceil((lines.length * 58) + pad * 1.4);
    g = cv.getContext('2d');
    g.font = font;
    g.textAlign = 'center';
    g.textBaseline = 'middle';
    lines.forEach(function (t, i) {
      g.fillStyle = colorCss;
      g.globalAlpha = i === 0 ? 0.96 : 0.6;
      g.fillText(t, cv.width / 2, pad * 0.8 + (i + 0.5) * 58);
    });
    var tex = new THREE.CanvasTexture(cv);
    tex.needsUpdate = true;
    var mat = new THREE.SpriteMaterial({
      map: tex, transparent: true, depthWrite: false,
      blending: THREE.AdditiveBlending,
    });
    var spr = new THREE.Sprite(mat);
    var k = (scaleUp || 1) * 0.026;
    spr.scale.set(cv.width * k, cv.height * k, 1);
    return spr;
  }

  // ── floor: the abyssal plain + its integer lattice ────────────────────
  var floor = new THREE.Mesh(
    new THREE.PlaneGeometry(1600, 1600),
    new THREE.MeshStandardMaterial({ color: C.floor, roughness: 1, metalness: 0 }));
  floor.rotation.x = -Math.PI / 2;
  scene.add(floor);

  var grid = new THREE.GridHelper(1600, 160, C.lattice, 0x0d1c36);
  grid.material.transparent = true;
  grid.material.opacity = 0.50;
  grid.position.y = 0.02;
  scene.add(grid);

  // marine snow — the abyss is never empty: a sparse static dust field that
  // makes motion readable while you walk. 14k motes, no updates per frame.
  // Seeded LCG, not Math.random — the same every load, like the rest of the map.
  (function marineSnow() {
    var seed = 0x445185a3;                       // the canon hash's high bits
    function rnd() { seed = (seed * 1664525 + 1013904223) >>> 0; return seed / 4294967296; }
    var n = 14000;
    var pos = new Float32Array(n * 3);
    for (var i = 0; i < n; i++) {
      pos[i * 3] = (rnd() - 0.5) * 720;
      pos[i * 3 + 1] = 0.2 + rnd() * rnd() * 20;
      pos[i * 3 + 2] = (rnd() - 0.5) * 720;
    }
    var geo = new THREE.BufferGeometry();
    geo.setAttribute('position', new THREE.BufferAttribute(pos, 3));
    scene.add(new THREE.Points(geo, new THREE.PointsMaterial({
      map: haloTexture('rgba(190,235,255,0.8)', 'rgba(120,190,220,0.25)'),
      color: 0x9fd8e8, size: 0.42, sizeAttenuation: true, transparent: true,
      opacity: 0.55, blending: THREE.AdditiveBlending, depthWrite: false,
    })));
  })();

  // ── rooms ─────────────────────────────────────────────────────────────
  var rooms = [];
  var emberRooms = [];
  var roomById = {};
  var pillarsById = {};

  WORLD.rooms.forEach(function (r) {
    var p = r.position || { x: 0, z: 0 };
    var synth = r.provenance === 'SYNTHETIC';
    var ember = !!r.ember;

    var emissive = ember ? C.ember : (synth ? C.steelDim : C.blue);
    var core = ember ? 0x2a1206 : (synth ? 0x0a1626 : C.blueCore);

    var dome = new THREE.Mesh(
      new THREE.SphereGeometry(ROOM_RADIUS, 30, 18),
      new THREE.MeshStandardMaterial({
        color: core, emissive: emissive, emissiveIntensity: ember ? 1.5 : 0.95,
        roughness: 0.38, metalness: 0.0, transparent: true, opacity: 0.94,
      }));
    dome.scale.set(1, 0.42, 1);
    dome.position.set(p.x, 0, p.z);
    scene.add(dome);

    // provenance ring: whole ring for REAL, broken ring for SYNTHETIC
    var ringGeo = synth
      ? new THREE.TorusGeometry(ROOM_RADIUS + 0.9, 0.055, 6, 40, Math.PI * 1.35)
      : new THREE.TorusGeometry(ROOM_RADIUS + 0.9, 0.06, 6, 48);
    var ring = new THREE.Mesh(ringGeo, new THREE.MeshBasicMaterial({
      color: ember ? C.emberSoft : (synth ? C.steelDim : C.mint),
      transparent: true, opacity: synth ? 0.5 : 0.8,
      blending: THREE.AdditiveBlending, depthWrite: false,
    }));
    ring.rotation.x = -Math.PI / 2;
    ring.position.set(p.x, 0.06, p.z);
    scene.add(ring);

    // halo — the bloom that makes it read as a living cell
    var halo = new THREE.Sprite(new THREE.SpriteMaterial({
      map: haloTexture(
        ember ? 'rgba(232,163,79,0.95)' : (synth ? 'rgba(120,170,205,0.55)' : 'rgba(82,242,200,0.55)'),
        ember ? 'rgba(200,86,30,0.45)' : (synth ? 'rgba(58,90,118,0.28)' : 'rgba(30,111,192,0.35)')),
      transparent: true, depthWrite: false, blending: THREE.AdditiveBlending,
      opacity: ember ? 0.95 : (synth ? 0.5 : 0.75),
    }));
    halo.position.set(p.x, 1.1, p.z);
    halo.scale.set(18, 18, 1);
    scene.add(halo);

    // label
    var tag = r.honestGap && r.honestGap.tagged ? (r.honestGap.status || 'HONEST GAP') : null;
    var labelText = 'r' + r.round + (tag ? ' · ' + tag : (synth ? ' · SYNTHETIC' : ''));
    var label = labelSprite([labelText],
      tag ? '#e8a34f' : (synth ? '#7fa8c8' : '#52f2c8'), 1);
    label.position.set(p.x, 5.0, p.z);
    scene.add(label);

    // ember pillar — visible across the floor; this is the wayfinding
    if (ember) {
      var pillar = new THREE.Mesh(
        new THREE.CylinderGeometry(1.6, 1.6, 120, 18, 1, true),
        new THREE.MeshBasicMaterial({
          color: C.ember, transparent: true, opacity: 0.11,
          blending: THREE.AdditiveBlending, depthWrite: false, side: THREE.DoubleSide,
        }));
      pillar.position.set(p.x, 60, p.z);
      scene.add(pillar);
      var glow = new THREE.PointLight(C.emberSoft, 1.7, 46);
      glow.position.set(p.x, 4, p.z);
      scene.add(glow);
      pillarsById[r.id] = pillar;
    }

    var entry = {
      data: r, dome: dome, ring: ring, halo: halo, label: label,
      base: { intensity: dome.material.emissiveIntensity, halo: halo.material.opacity },
      visited: false,
    };
    rooms.push(entry);
    roomById[r.id] = entry;
  });

  // the ember rooms (built after the loop, so entries carry dome + halo + pillar)
  rooms.forEach(function (entry) {
    if (entry.data.ember) {
      entry.pillar = pillarsById[entry.data.id];
      emberRooms.push(entry);
    }
  });

  // ── trails: the ancestry edges, lit ───────────────────────────────────
  var trailMats = {
    REAL: new THREE.MeshBasicMaterial({
      color: C.mint, transparent: true, opacity: 0.62,
      blending: THREE.AdditiveBlending, depthWrite: false,
    }),
    SYNTHETIC: new THREE.MeshBasicMaterial({
      color: C.steel, transparent: true, opacity: 0.26,
      blending: THREE.AdditiveBlending, depthWrite: false,
    }),
  };
  var drawnSeg = {};   // "a~b" — a segment shared by two walks is drawn once

  function trailCurve(a, b) {
    var va = new THREE.Vector3(a.position.x, 0.32, a.position.z);
    var vb = new THREE.Vector3(b.position.x, 0.32, b.position.z);
    var mid = va.clone().add(vb).multiplyScalar(0.5);
    var dir = vb.clone().sub(va).normalize();
    var bow = new THREE.Vector3(-dir.z, 0, dir.x).multiplyScalar(va.distanceTo(vb) * 0.10);
    mid.add(bow);
    mid.y = 1.9;
    var q1 = va.clone().lerp(mid, 0.5); q1.y = 0.9;
    var q2 = mid.clone().lerp(vb, 0.5); q2.y = 0.9;
    return new THREE.CatmullRomCurve3([va, q1, mid, q2, vb]);
  }

  (WORLD.walks || []).forEach(function (walk) {
    if (!walk || !Array.isArray(walk.segments)) return;
    walk.segments.forEach(function (s) {
      var a = roomById[s.from];
      var b = roomById[s.to];
      if (!a || !b) return;
      // a segment already drawn by another walk needs no second tube
      var key = [s.from, s.to].sort().join('~');
      if (drawnSeg[key]) return;
      drawnSeg[key] = true;

      var prov = s.provenance === 'SYNTHETIC' ? 'SYNTHETIC' : 'REAL';
      var curve = trailCurve(a.data, b.data);
      scene.add(new THREE.Mesh(
        new THREE.TubeGeometry(curve, 44, 0.13, 6, false), trailMats[prov]));

      // plankton along the trail — the lit path you follow
      var n = 26;
      var pos = new Float32Array(n * 3);
      for (var i = 0; i < n; i++) {
        var pt = curve.getPoint((i + 0.5) / n);
        pos[i * 3] = pt.x;
        pos[i * 3 + 1] = pt.y + Math.sin(i * 1.7) * 0.18;
        pos[i * 3 + 2] = pt.z;
      }
      var geo = new THREE.BufferGeometry();
      geo.setAttribute('position', new THREE.BufferAttribute(pos, 3));
      scene.add(new THREE.Points(geo, new THREE.PointsMaterial({
        map: haloTexture('rgba(255,255,255,0.95)', 'rgba(255,255,255,0.35)'),
        color: prov === 'SYNTHETIC' ? C.steel : C.mint,
        size: 0.55, sizeAttenuation: true, transparent: true,
        opacity: prov === 'SYNTHETIC' ? 0.4 : 0.85,
        blending: THREE.AdditiveBlending, depthWrite: false,
      })));
    });
  });

  // ── landmarks: the midden's other REAL fixtures ───────────────────────
  var LM = WORLD.landmarks || {};
  var spinners = [];
  var bells = [];

  // ridges — the-tap values ledger, strength = elevation (distant silhouettes)
  (LM.ridges && LM.ridges.items ? LM.ridges.items : []).forEach(function (rg, i, arr) {
    var a = -Math.PI * 0.42 + (i / Math.max(1, arr.length - 1)) * Math.PI * 0.95;
    var rad = 336 + (i % 3) * 22;
    var h = 14 + rg.strength * 52;
    var ridge = new THREE.Mesh(
      new THREE.ConeGeometry(20 + rg.evidence * 1.6, h, 5),
      new THREE.MeshStandardMaterial({ color: 0x050c18, roughness: 1, metalness: 0 }));
    ridge.position.set(Math.sin(a) * rad, h / 2 - 2, -Math.abs(Math.cos(a)) * rad - 40);
    scene.add(ridge);
  });

  // the choir — 7 commensuration teeth on the horizon
  (LM.choir && LM.choir.items ? LM.choir.items : []).forEach(function (tooth, i) {
    var a = Math.PI * 0.18 + (i / 6) * Math.PI * 0.64;
    var rad = 352;
    var bell = new THREE.Mesh(
      new THREE.TorusGeometry(4.6, 0.16, 6, 40),
      new THREE.MeshBasicMaterial({
        color: C.emberSoft, transparent: true, opacity: 0.5,
        blending: THREE.AdditiveBlending, depthWrite: false,
      }));
    bell.position.set(Math.sin(a) * rad, 14 + i * 3.4, -Math.cos(a) * rad);
    bell.lookAt(0, 14 + i * 3.4, 0);
    scene.add(bell);
    bells.push({ mesh: bell, phase: i * 0.9, base: 0.5 });
  });

  // the Drown — real unACKed canon edges, voids in the low ground.
  // Each void is pushed out of the room corridor so nothing overlaps a cell.
  function clearOfRooms(x, z, minDist) {
    for (var tries = 0; tries < 60; tries++) {
      var nearest = null;
      var nd = Infinity;
      rooms.forEach(function (r) {
        var dx = x - r.dome.position.x;
        var dz = z - r.dome.position.z;
        var d = Math.sqrt(dx * dx + dz * dz);
        if (d < nd) { nd = d; nearest = { dx: dx, dz: dz, d: d }; }
      });
      if (!nearest || nearest.d >= minDist) return { x: x, z: z };
      var len = nearest.d || 1;
      x += (nearest.dx / len) * (minDist - nearest.d + 2);
      z += (nearest.dz / len) * (minDist - nearest.d + 2);
    }
    return { x: x, z: z };
  }

  (LM.whirlpools && LM.whirlpools.items ? LM.whirlpools.items : []).forEach(function (wp, i) {
    var a = Math.PI * (0.60 + i * 0.20);
    var rad = 148 + i * 24;
    var spot = clearOfRooms(Math.sin(a) * rad, Math.cos(a) * rad + 40, 20);
    var x = spot.x;
    var z = spot.z;
    var void_ = new THREE.Mesh(
      new THREE.CircleGeometry(7.5, 40),
      new THREE.MeshBasicMaterial({ color: 0x000000 }));
    void_.rotation.x = -Math.PI / 2;
    void_.position.set(x, 0.04, z);
    scene.add(void_);
    var lip = new THREE.Mesh(
      new THREE.TorusGeometry(8.2, 0.22, 6, 48),
      new THREE.MeshBasicMaterial({
        color: C.lattice, transparent: true, opacity: 0.75,
        blending: THREE.AdditiveBlending, depthWrite: false,
      }));
    lip.rotation.x = -Math.PI / 2;
    lip.position.set(x, 0.08, z);
    scene.add(lip);
    spinners.push(lip);
    var lbl = labelSprite([wp.id], '#7fa8c8', 0.8);
    lbl.position.set(x, 3.2, z);
    scene.add(lbl);
  });

  // the sky — 16 stars fixed at the canon hash digits
  (LM.sky && LM.sky.digitValues ? LM.sky.digitValues : []).forEach(function (d, i) {
    var az = (d / 16) * Math.PI * 2 + 0.18;
    var el = 0.30 + ((i % 5) / 5) * 0.55;
    var rad = 520;
    var pos = new Float32Array(3);
    pos[0] = Math.sin(az) * Math.cos(el) * rad;
    pos[1] = Math.sin(el) * rad;
    pos[2] = Math.cos(az) * Math.cos(el) * rad;
    var geo = new THREE.BufferGeometry();
    geo.setAttribute('position', new THREE.BufferAttribute(pos, 3));
    scene.add(new THREE.Points(geo, new THREE.PointsMaterial({
      map: haloTexture('rgba(255,255,255,0.9)', 'rgba(207,216,230,0.35)'),
      color: C.text, size: 9, sizeAttenuation: true, transparent: true,
      blending: THREE.AdditiveBlending, depthWrite: false,
    })));
  });

  // ── controls ──────────────────────────────────────────────────────────
  var yaw = 0, pitch = -0.05;   // facing -z, into the floor of rooms
  var keys = {};
  var locked = false;
  var showLabels = true;
  var auto = { on: false, idx: 0 };
  var autoWalk = (WORLD.walks || []).filter(function (w) { return w.id === 'the-whole-floor'; })[0];

  var overlay = document.getElementById('overlay');
  var hintEl = document.getElementById('hud-hint');

  overlay.addEventListener('click', function () { canvas.requestPointerLock(); });
  canvas.addEventListener('click', function () { if (!locked) canvas.requestPointerLock(); });

  document.addEventListener('pointerlockchange', function () {
    locked = document.pointerLockElement === canvas;
    overlay.style.display = locked ? 'none' : 'flex';
    if (!locked) { auto.on = false; for (var k in keys) keys[k] = false; }
  });

  document.addEventListener('mousemove', function (e) {
    if (!locked) return;
    yaw -= e.movementX * 0.0022;
    pitch -= e.movementY * 0.0022;
    pitch = Math.max(-1.45, Math.min(1.45, pitch));
  });

  function cancelAuto() { if (auto.on) { auto.on = false; } }

  document.addEventListener('keydown', function (e) {
    var k = e.key.toLowerCase();
    if (k === 'f') {
      if (autoWalk && autoWalk.rooms && autoWalk.rooms.length) {
        auto.on = !auto.on;
        if (auto.on) auto.idx = nearestRoomIndex();
      }
      return;
    }
    if (k === 'l') { showLabels = !showLabels; return; }
    if (k === 'h') { hintEl.style.display = hintEl.style.display === 'none' ? '' : 'none'; return; }
    if (['w', 'a', 's', 'd', 'arrowup', 'arrowdown', 'arrowleft', 'arrowright', 'shift'].indexOf(k) >= 0) {
      keys[k] = true;
      if (k !== 'shift') cancelAuto();
      e.preventDefault();
    }
  });
  document.addEventListener('keyup', function (e) {
    keys[e.key.toLowerCase()] = false;
  });

  function nearestRoomIndex() {
    var best = 0;
    var bd = Infinity;
    rooms.forEach(function (r, i) {
      var d = r.dome.position.distanceToSquared(camera.position);
      if (d < bd) { bd = d; best = i; }
    });
    return best;
  }

  // ── HUD ───────────────────────────────────────────────────────────────
  var hudRoom = document.getElementById('hud-room');
  var hudNear = document.getElementById('hud-near');
  var elName = hudRoom.querySelector('.name');
  var elBadge = hudRoom.querySelector('.badge');
  var elTag = hudRoom.querySelector('.gap-tag');
  var elNums = hudRoom.querySelector('.nums');
  var elLine = hudRoom.querySelector('.line');
  var elMethod = hudRoom.querySelector('.method');

  function thousands(x) {
    var s = String(x);
    var i = s.indexOf('.');
    var whole = i < 0 ? s : s.slice(0, i);
    var frac = i < 0 ? '' : s.slice(i);
    return whole.replace(/\B(?=(\d{3})+(?!\d))/g, ',') + frac;
  }
  function fx(x, d) { return (typeof x === 'number') ? x.toFixed(d === undefined ? 4 : d) : '—'; }

  function showRoom(r) {
    var synth = r.provenance === 'SYNTHETIC';
    var gapTag = r.honestGap && r.honestGap.tagged ? (r.honestGap.status || 'HONEST GAP') : null;

    elName.textContent = r.label;
    elBadge.textContent = r.provenance;
    elBadge.className = 'badge ' + (synth ? 'synthetic' : 'real');
    elTag.textContent = gapTag ? '◆ ' + gapTag : '';
    elTag.style.display = gapTag ? '' : 'none';

    var ro = r.readout || {};
    var pairs = [
      ['round', String(r.round)],
      ['σ', fx(r && ro.sigma, 4)],
      ['arc', thousands(fx(ro.arcLength, 1))],
      ['bend', fx(ro.bendingEnergy)],
      ['torsion', fx(ro.torsion, 6)],
      ['planarity', fx(ro.planarity, 6)],
    ];
    elNums.innerHTML = pairs.map(function (pr) {
      return '<dt>' + pr[0] + '</dt><dd>' + pr[1] + '</dd>';
    }).join('');

    if (gapTag && WORLD.gap) {
      elLine.textContent = WORLD.gap.line || '';
      elLine.style.display = '';
    } else if (gapTag) {
      elLine.style.display = 'none';
    } else {
      elLine.style.display = 'none';
    }

    elMethod.textContent = synth && r.method
      ? 'SYNTHETIC — ' + r.method
      : (synth ? 'SYNTHETIC' : '');
    elMethod.style.display = elMethod.textContent ? '' : 'none';
    hudRoom.style.display = 'block';
  }

  function hideRoom() { hudRoom.style.display = 'none'; }

  // ── loop ──────────────────────────────────────────────────────────────
  var clock = new THREE.Clock();
  var vel = new THREE.Vector3();
  var dir = new THREE.Vector3();
  var tmp = new THREE.Vector3();
  var shown = null;

  function move(dt) {
    var target = null;

    if (auto.on && autoWalk) {
      var ids = autoWalk.rooms;
      var goal = roomById[ids[Math.min(auto.idx, ids.length - 1)]];
      if (goal) {
        tmp.set(goal.dome.position.x - camera.position.x, 0,
                goal.dome.position.z - camera.position.z);
        var dist = tmp.length();
        if (dist < 3.0 && auto.idx < ids.length - 1) {
          auto.idx += 1;
        } else if (dist < 2.2) {
          auto.on = false;
        } else {
          target = tmp.clone().normalize();
          var want = Math.atan2(-target.x, -target.z);
          var dy = want - yaw;
          while (dy > Math.PI) dy -= Math.PI * 2;
          while (dy < -Math.PI) dy += Math.PI * 2;
          yaw += dy * Math.min(1, dt * 3.2);
          pitch += (-0.20 - pitch) * Math.min(1, dt * 2.0);
        }
      }
    }

    var f = (keys.w || keys.arrowup ? 1 : 0) - (keys.s || keys.arrowdown ? 1 : 0);
    var s = (keys.d || keys.arrowright ? 1 : 0) - (keys.a || keys.arrowleft ? 1 : 0);

    dir.set(0, 0, 0);
    if (!target) {
      var fwd = new THREE.Vector3(-Math.sin(yaw), 0, -Math.cos(yaw));
      var right = new THREE.Vector3(Math.cos(yaw), 0, -Math.sin(yaw));
      dir.addScaledVector(fwd, f).addScaledVector(right, s);
      if (dir.lengthSq() > 0) dir.normalize();
    } else {
      dir.copy(target);
    }

    var speed = (keys.shift ? RUN_SPEED : WALK_SPEED) * (target ? AUTO_SPEED / WALK_SPEED : 1);
    var desired = dir.multiplyScalar(speed);
    vel.lerp(desired, Math.min(1, dt * 9));

    camera.position.x += vel.x * dt;
    camera.position.z += vel.z * dt;
    camera.position.y = EYE + Math.sin(clock.elapsedTime * 9) * 0.035 *
      Math.min(1, vel.length() / WALK_SPEED);

    var lim = 520;
    camera.position.x = Math.max(-lim, Math.min(lim, camera.position.x));
    camera.position.z = Math.max(-lim, Math.min(lim, camera.position.z));
  }

  function animate() {
    requestAnimationFrame(animate);
    var dt = Math.min(clock.getDelta(), 0.05);
    var t = clock.elapsedTime;

    move(dt);
    camera.rotation.set(pitch, yaw, 0);

    // ember rooms pulse; everything else breathes very slowly
    emberRooms.forEach(function (er, i) {
      var pulse = 0.5 + 0.5 * Math.sin(t * 2.1 + i);
      er.dome.material.emissiveIntensity = 1.15 + pulse * 1.15;
      er.halo.material.opacity = 0.62 + pulse * 0.38;
      var sc = 1 + pulse * 0.07;
      er.halo.scale.set(18 * sc, 18 * sc, 1);
      if (er.pillar) er.pillar.material.opacity = 0.085 + pulse * 0.09;
    });
    bells.forEach(function (b, i) {
      b.mesh.material.opacity = b.base + 0.22 * (0.5 + 0.5 * Math.sin(t * 0.9 + b.phase));
    });
    spinners.forEach(function (sp) { sp.rotation.z += dt * 0.45; });

    // nearest-room pickup + quiet highlighting
    var ni = nearestRoomIndex();
    var near = rooms[ni];
    var d = near.dome.position.distanceTo(camera.position);
    rooms.forEach(function (r, i) {
      var isNear = i === ni && d < 15;
      var isEmber = r.data.ember;
      r.dome.material.emissiveIntensity = isEmber
        ? r.dome.material.emissiveIntensity
        : (r.base.intensity * (isNear ? 1.55 : 1.0));
      r.halo.material.opacity = isEmber
        ? r.halo.material.opacity
        : r.base.halo * (isNear ? 1.3 : 1.0);
      if (r.label) r.label.visible = showLabels;
      if (isNear && !r.visited) r.visited = true;
    });

    if (d < 15) {
      if (shown !== near.data) { showRoom(near.data); shown = near.data; }
    } else if (shown) {
      hideRoom();
      shown = null;
    }

    if (roomLight) {
      roomLight.position.set(near.dome.position.x, 3.2, near.dome.position.z);
      roomLight.intensity = d < 26 ? 0.85 * (1 - d / 26) : 0;
    }

    var bearing = rooms.reduce(function (acc, r) {
      return r.data.ember ? r : acc;
    }, null);
    if (bearing && hudNear) {
      var eb = bearing.dome.position.distanceTo(camera.position);
      hudNear.textContent = 'nearest r' + near.data.round + ' · ' + d.toFixed(1) +
        ' m   |   the gap r' + bearing.data.round + ' · ' + eb.toFixed(0) + ' m';
    }

    renderer.render(scene, camera);
  }

  window.addEventListener('resize', function () {
    camera.aspect = window.innerWidth / window.innerHeight;
    camera.updateProjectionMatrix();
    renderer.setSize(window.innerWidth, window.innerHeight);
  });

  // ── deep links ────────────────────────────────────────────────────────
  // #r7            stand in front of room r7, facing it
  // #at=r7&enter=1 same, and skip the intro card
  // #walk=1        start the trail autopilot on load (no pointer lock needed)
  // Pointer lock still needs a click — the canvas click handler keeps working.
  (function deepLink() {
    var h = (window.location.hash || '').replace(/^#/, '');
    if (!h) return;
    var params = {};
    h.split('&').forEach(function (kv) {
      var p = kv.split('=');
      params[p[0]] = p.length > 1 ? p[1] : true;
    });
    var target = params.at || (/^r\d+$/.test(h) ? h : null);
    if (target && roomById[target]) {
      var pos = roomById[target].dome.position;
      camera.position.set(pos.x, EYE, pos.z + 13);
      yaw = Math.atan2(-(pos.x - camera.position.x), -(pos.z - camera.position.z));
      pitch = -0.08;
    }
    if (params.walk && autoWalk) { auto.on = true; auto.idx = nearestRoomIndex(); }
    if (params.enter || params.walk || target) overlay.style.display = 'none';
  })();

  animate();
})();
