/* world-data.js — GENERATED by tools/gen-world.mjs. Do not edit by hand.
 * Inlined as a global so world/index.html boots from file:// (no fetch, no modules).
 * Regenerate: node tools/gen-world.mjs
 */
window.WORLD = {
  "schema": "midden.world/1",
  "generatedBy": "node tools/gen-world.mjs",
  "title": "the midden — the floor you can walk",
  "note": "rooms are the rounds of the rescued Q^16 walk, laid out on the two highest-variance REAL feature axes; trails are the ancestry edges. The verdict round is the ember room.",
  "provenance": {
    "source": "SuperInstance/q16-trajectories @ lane-n-q16-bridge bfd7ee8 (src/breed.js, src/lineage.js)",
    "seed": "q16/midden-at-dusk",
    "artist": "duke",
    "persona": "purist",
    "featuresOrder": [
      "registerSpread",
      "trebleActivity",
      "dynRange",
      "dynContour",
      "swingFeel",
      "syncopation",
      "downbeatWeight",
      "harmonicComplex",
      "chromaticism",
      "repetition",
      "callReply",
      "density",
      "phraseVariance",
      "restRatio",
      "bassMovement",
      "cadenceRegular"
    ],
    "realRounds": 8,
    "syntheticRounds": 4,
    "syntheticMethod": "damped per-feature least-squares slope over real rounds 4..7, decay 0.85 per step, clamped to the walk's own [0, 1000000] Q-range, rounded to integers. Deterministic; no randomness, no model output, no verdict.",
    "layoutAxes": {
      "x": 2,
      "z": 15,
      "rule": "highest per-feature variance across the REAL rounds only"
    }
  },
  "dims": {
    "n": 16,
    "nRounds": 12,
    "nRealRounds": 8
  },
  "rooms": [
    {
      "id": "r0",
      "round": 0,
      "label": "round 0",
      "provenance": "REAL",
      "honestGap": {
        "tagged": false,
        "status": null
      },
      "ember": false,
      "position": {
        "x": -130,
        "z": 100,
        "y": 0,
        "i": 0
      },
      "readout": {
        "arcLength": 0,
        "bendingEnergy": 0,
        "torsion": 0,
        "planarity": 1,
        "sigma": 0.1721
      }
    },
    {
      "id": "r1",
      "round": 1,
      "label": "round 1",
      "provenance": "REAL",
      "honestGap": {
        "tagged": false,
        "status": null
      },
      "ember": false,
      "position": {
        "x": 58.983,
        "z": -100,
        "y": 0,
        "i": 1
      },
      "readout": {
        "arcLength": 385447.27,
        "bendingEnergy": 0,
        "torsion": 0,
        "planarity": 1,
        "sigma": 0.1156
      }
    },
    {
      "id": "r2",
      "round": 2,
      "label": "round 2",
      "provenance": "REAL",
      "honestGap": {
        "tagged": false,
        "status": null
      },
      "ember": false,
      "position": {
        "x": 61.666,
        "z": -100,
        "y": 0,
        "i": 2
      },
      "readout": {
        "arcLength": 525928.8051,
        "bendingEnergy": 1.0318,
        "torsion": 0,
        "planarity": 1,
        "sigma": 0.1237
      }
    },
    {
      "id": "r3",
      "round": 3,
      "label": "round 3",
      "provenance": "REAL",
      "honestGap": {
        "tagged": false,
        "status": null
      },
      "ember": false,
      "position": {
        "x": 92.313,
        "z": -60,
        "y": 0,
        "i": 3
      },
      "readout": {
        "arcLength": 661854.0851,
        "bendingEnergy": 2.151,
        "torsion": 0.9881,
        "planarity": 0.50595,
        "sigma": 0.1218
      }
    },
    {
      "id": "r4",
      "round": 4,
      "label": "round 4",
      "provenance": "REAL",
      "honestGap": {
        "tagged": false,
        "status": null
      },
      "ember": false,
      "position": {
        "x": 116.094,
        "z": -100,
        "y": 0,
        "i": 4
      },
      "readout": {
        "arcLength": 782666.7664,
        "bendingEnergy": 3.46,
        "torsion": 1.926347,
        "planarity": 0.357884,
        "sigma": 0.1203
      }
    },
    {
      "id": "r5",
      "round": 5,
      "label": "round 5",
      "provenance": "REAL",
      "honestGap": {
        "tagged": false,
        "status": null
      },
      "ember": false,
      "position": {
        "x": 118.919,
        "z": -20,
        "y": 0,
        "i": 5
      },
      "readout": {
        "arcLength": 1025476.0699,
        "bendingEnergy": 5.0436,
        "torsion": 2.732037,
        "planarity": 0.316991,
        "sigma": 0.1144
      }
    },
    {
      "id": "r6",
      "round": 6,
      "label": "round 6",
      "provenance": "REAL",
      "honestGap": {
        "tagged": false,
        "status": null
      },
      "ember": false,
      "position": {
        "x": 130,
        "z": -20,
        "y": 0,
        "i": 6
      },
      "readout": {
        "arcLength": 1158131.3761,
        "bendingEnergy": 6.755,
        "torsion": 3.420749,
        "planarity": 0.31585,
        "sigma": 0.1151
      }
    },
    {
      "id": "r7",
      "round": 7,
      "label": "round 7 — the gap (verdict)",
      "provenance": "REAL",
      "honestGap": {
        "tagged": true,
        "status": "HONEST GAP"
      },
      "ember": true,
      "position": {
        "x": 69.627,
        "z": -100,
        "y": 0,
        "i": 7
      },
      "readout": {
        "arcLength": 1328817.932,
        "bendingEnergy": 7.8186,
        "torsion": 3.964612,
        "planarity": 0.339231,
        "sigma": 0.1185
      }
    },
    {
      "id": "r8",
      "round": 8,
      "label": "round 8 — after the gap",
      "provenance": "SYNTHETIC",
      "method": "damped per-feature least-squares slope over real rounds 4..7, decay 0.85 per step, clamped to the walk's own [0, 1000000] Q-range, rounded to integers. Deterministic; no randomness, no model output, no verdict.",
      "honestGap": {
        "tagged": false,
        "status": null
      },
      "ember": false,
      "position": {
        "x": 58.72,
        "z": -100,
        "y": 0,
        "i": 8
      },
      "readout": {
        "arcLength": 1352903.8503,
        "bendingEnergy": 8.5812,
        "torsion": 4.93574,
        "planarity": 0.294894,
        "sigma": 0.1173
      }
    },
    {
      "id": "r9",
      "round": 9,
      "label": "round 9 — after the gap",
      "provenance": "SYNTHETIC",
      "method": "damped per-feature least-squares slope over real rounds 4..7, decay 0.85 per step, clamped to the walk's own [0, 1000000] Q-range, rounded to integers. Deterministic; no randomness, no model output, no verdict.",
      "honestGap": {
        "tagged": false,
        "status": null
      },
      "ember": false,
      "position": {
        "x": 49.449,
        "z": -100,
        "y": 0,
        "i": 9
      },
      "readout": {
        "arcLength": 1373376.7383,
        "bendingEnergy": 8.5812,
        "torsion": 4.935801,
        "planarity": 0.383025,
        "sigma": 0.115
      }
    },
    {
      "id": "r10",
      "round": 10,
      "label": "round 10 — after the gap",
      "provenance": "SYNTHETIC",
      "method": "damped per-feature least-squares slope over real rounds 4..7, decay 0.85 per step, clamped to the walk's own [0, 1000000] Q-range, rounded to integers. Deterministic; no randomness, no model output, no verdict.",
      "honestGap": {
        "tagged": false,
        "status": null
      },
      "ember": false,
      "position": {
        "x": 41.569,
        "z": -100,
        "y": 0,
        "i": 10
      },
      "readout": {
        "arcLength": 1390779.1794,
        "bendingEnergy": 8.5812,
        "torsion": 4.935827,
        "planarity": 0.451575,
        "sigma": 0.1115
      }
    },
    {
      "id": "r11",
      "round": 11,
      "label": "round 11 — after the gap",
      "provenance": "SYNTHETIC",
      "method": "damped per-feature least-squares slope over real rounds 4..7, decay 0.85 per step, clamped to the walk's own [0, 1000000] Q-range, rounded to integers. Deterministic; no randomness, no model output, no verdict.",
      "honestGap": {
        "tagged": false,
        "status": null
      },
      "ember": false,
      "position": {
        "x": 34.871,
        "z": -100,
        "y": 0,
        "i": 11
      },
      "readout": {
        "arcLength": 1405570.3712,
        "bendingEnergy": 8.5812,
        "torsion": 4.935885,
        "planarity": 0.506411,
        "sigma": 0.107
      }
    }
  ],
  "walks": [
    {
      "id": "rescued-walk",
      "label": "the rescued walk (real — the one duke-lab threw away)",
      "provenance": "REAL",
      "rooms": [
        "r0",
        "r1",
        "r2",
        "r3",
        "r4",
        "r5",
        "r6",
        "r7"
      ],
      "segments": [
        {
          "from": "r0",
          "to": "r1",
          "provenance": "REAL",
          "driftQ": 1012218,
          "sigmaDrop": 0.05650000000000001,
          "planarityFrom": 1,
          "planarityTo": 1,
          "planarityDelta": 0,
          "torsion": 0,
          "arc": 385447.27
        },
        {
          "from": "r1",
          "to": "r2",
          "provenance": "REAL",
          "driftQ": 325489,
          "sigmaDrop": -0.00810000000000001,
          "planarityFrom": 1,
          "planarityTo": 1,
          "planarityDelta": 0,
          "torsion": 0,
          "arc": 140481.5351
        },
        {
          "from": "r2",
          "to": "r3",
          "provenance": "REAL",
          "driftQ": 398909,
          "sigmaDrop": 0.001899999999999999,
          "planarityFrom": 1,
          "planarityTo": 0.50595,
          "planarityDelta": -0.49405,
          "torsion": 0.9881,
          "arc": 135925.2799
        },
        {
          "from": "r3",
          "to": "r4",
          "provenance": "REAL",
          "driftQ": 391979,
          "sigmaDrop": 0.0015000000000000013,
          "planarityFrom": 0.50595,
          "planarityTo": 0.357884,
          "planarityDelta": -0.148066,
          "torsion": 0.938247,
          "arc": 120812.6813
        },
        {
          "from": "r4",
          "to": "r5",
          "provenance": "REAL",
          "driftQ": 550194,
          "sigmaDrop": 0.0059000000000000025,
          "planarityFrom": 0.357884,
          "planarityTo": 0.316991,
          "planarityDelta": -0.040894,
          "torsion": 0.80569,
          "arc": 242809.3035
        },
        {
          "from": "r5",
          "to": "r6",
          "provenance": "REAL",
          "driftQ": 329192,
          "sigmaDrop": -0.0006999999999999923,
          "planarityFrom": 0.316991,
          "planarityTo": 0.31585,
          "planarityDelta": -0.00114,
          "torsion": 0.688711,
          "arc": 132655.3062
        },
        {
          "from": "r6",
          "to": "r7",
          "provenance": "REAL",
          "driftQ": 477993,
          "sigmaDrop": -0.0034000000000000002,
          "planarityFrom": 0.31585,
          "planarityTo": 0.339231,
          "planarityDelta": 0.023381,
          "torsion": 0.543864,
          "arc": 170686.5559
        }
      ]
    },
    {
      "id": "what-comes-next",
      "label": "what comes next (SYNTHETIC — continuation past the gap)",
      "provenance": "SYNTHETIC",
      "method": "damped per-feature least-squares slope over real rounds 4..7, decay 0.85 per step, clamped to the walk's own [0, 1000000] Q-range, rounded to integers. Deterministic; no randomness, no model output, no verdict.",
      "rooms": [
        "r7",
        "r8",
        "r9",
        "r10",
        "r11"
      ],
      "segments": [
        {
          "from": "r7",
          "to": "r8",
          "provenance": "SYNTHETIC",
          "driftQ": null,
          "sigmaDrop": null,
          "planarityFrom": 0.339231,
          "planarityTo": 0.294894,
          "planarityDelta": -0.044337,
          "torsion": 0.971128,
          "arc": 24085.9183
        },
        {
          "from": "r8",
          "to": "r9",
          "provenance": "SYNTHETIC",
          "driftQ": null,
          "sigmaDrop": null,
          "planarityFrom": 0.294894,
          "planarityTo": 0.383025,
          "planarityDelta": 0.088131,
          "torsion": 0.000061,
          "arc": 20472.888
        },
        {
          "from": "r9",
          "to": "r10",
          "provenance": "SYNTHETIC",
          "driftQ": null,
          "sigmaDrop": null,
          "planarityFrom": 0.383025,
          "planarityTo": 0.451575,
          "planarityDelta": 0.06855,
          "torsion": 0.000026,
          "arc": 17402.4412
        },
        {
          "from": "r10",
          "to": "r11",
          "provenance": "SYNTHETIC",
          "driftQ": null,
          "sigmaDrop": null,
          "planarityFrom": 0.451575,
          "planarityTo": 0.506411,
          "planarityDelta": 0.054837,
          "torsion": 0.000058,
          "arc": 14791.1918
        }
      ]
    },
    {
      "id": "the-whole-floor",
      "label": "the whole floor (real walk, then the labeled continuation)",
      "provenance": "MIXED",
      "rooms": [
        "r0",
        "r1",
        "r2",
        "r3",
        "r4",
        "r5",
        "r6",
        "r7",
        "r8",
        "r9",
        "r10",
        "r11"
      ],
      "segments": [
        {
          "from": "r0",
          "to": "r1",
          "provenance": "REAL",
          "driftQ": 1012218,
          "sigmaDrop": 0.05650000000000001,
          "planarityFrom": 1,
          "planarityTo": 1,
          "planarityDelta": 0,
          "torsion": 0,
          "arc": 385447.27
        },
        {
          "from": "r1",
          "to": "r2",
          "provenance": "REAL",
          "driftQ": 325489,
          "sigmaDrop": -0.00810000000000001,
          "planarityFrom": 1,
          "planarityTo": 1,
          "planarityDelta": 0,
          "torsion": 0,
          "arc": 140481.5351
        },
        {
          "from": "r2",
          "to": "r3",
          "provenance": "REAL",
          "driftQ": 398909,
          "sigmaDrop": 0.001899999999999999,
          "planarityFrom": 1,
          "planarityTo": 0.50595,
          "planarityDelta": -0.49405,
          "torsion": 0.9881,
          "arc": 135925.2799
        },
        {
          "from": "r3",
          "to": "r4",
          "provenance": "REAL",
          "driftQ": 391979,
          "sigmaDrop": 0.0015000000000000013,
          "planarityFrom": 0.50595,
          "planarityTo": 0.357884,
          "planarityDelta": -0.148066,
          "torsion": 0.938247,
          "arc": 120812.6813
        },
        {
          "from": "r4",
          "to": "r5",
          "provenance": "REAL",
          "driftQ": 550194,
          "sigmaDrop": 0.0059000000000000025,
          "planarityFrom": 0.357884,
          "planarityTo": 0.316991,
          "planarityDelta": -0.040894,
          "torsion": 0.80569,
          "arc": 242809.3035
        },
        {
          "from": "r5",
          "to": "r6",
          "provenance": "REAL",
          "driftQ": 329192,
          "sigmaDrop": -0.0006999999999999923,
          "planarityFrom": 0.316991,
          "planarityTo": 0.31585,
          "planarityDelta": -0.00114,
          "torsion": 0.688711,
          "arc": 132655.3062
        },
        {
          "from": "r6",
          "to": "r7",
          "provenance": "REAL",
          "driftQ": 477993,
          "sigmaDrop": -0.0034000000000000002,
          "planarityFrom": 0.31585,
          "planarityTo": 0.339231,
          "planarityDelta": 0.023381,
          "torsion": 0.543864,
          "arc": 170686.5559
        },
        {
          "from": "r7",
          "to": "r8",
          "provenance": "SYNTHETIC",
          "driftQ": null,
          "sigmaDrop": null,
          "planarityFrom": 0.339231,
          "planarityTo": 0.294894,
          "planarityDelta": -0.044337,
          "torsion": 0.971128,
          "arc": 24085.9183
        },
        {
          "from": "r8",
          "to": "r9",
          "provenance": "SYNTHETIC",
          "driftQ": null,
          "sigmaDrop": null,
          "planarityFrom": 0.294894,
          "planarityTo": 0.383025,
          "planarityDelta": 0.088131,
          "torsion": 0.000061,
          "arc": 20472.888
        },
        {
          "from": "r9",
          "to": "r10",
          "provenance": "SYNTHETIC",
          "driftQ": null,
          "sigmaDrop": null,
          "planarityFrom": 0.383025,
          "planarityTo": 0.451575,
          "planarityDelta": 0.06855,
          "torsion": 0.000026,
          "arc": 17402.4412
        },
        {
          "from": "r10",
          "to": "r11",
          "provenance": "SYNTHETIC",
          "driftQ": null,
          "sigmaDrop": null,
          "planarityFrom": 0.451575,
          "planarityTo": 0.506411,
          "planarityDelta": 0.054837,
          "torsion": 0.000058,
          "arc": 14791.1918
        }
      ]
    }
  ],
  "gap": {
    "round": 7,
    "status": "HONEST GAP",
    "sigma": 0.11847104064430357,
    "residueDims": 12,
    "planarityAtGap": 0.339231,
    "neighbors": {
      "rounds": [
        6,
        5
      ],
      "values": [
        0.31585,
        0.316991
      ]
    },
    "corroborated": true,
    "kind": "hesitation",
    "torsionStepIntoGap": 0.543864,
    "priorPerVertexMean": 0.68415,
    "arcStepIntoGap": 170686.5559,
    "line": "planarity corroborates the gap (r7 = 0.3392 vs neighbors 0.3159, 0.3170) — the step into round 7 adds torsion 0.5439, ~21% below the prior per-vertex mean 0.6842: a hesitation, not a flattening"
  },
  "instrumentChecks": [
    {
      "name": "planarity r5",
      "ok": true
    },
    {
      "name": "planarity r6",
      "ok": true
    },
    {
      "name": "planarity r7",
      "ok": true
    },
    {
      "name": "torsion r6",
      "ok": true
    },
    {
      "name": "torsion r7",
      "ok": true
    },
    {
      "name": "arc r6",
      "ok": true
    },
    {
      "name": "arc r7",
      "ok": true
    }
  ]
};
